import { writeFileSync } from "node:fs";
import { join } from "node:path";

function envLine(key: string, value: string): string {
  const needsQuotes = /[\s#"'\\]/.test(value);
  if (!needsQuotes) {
    return `${key}=${value}`;
  }
  const escaped = value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  return `${key}="${escaped}"`;
}

const deployKey = process.env.CONVEX_DEPLOY_KEY;
const convexUrl = process.env.VITE_CONVEX_URL;

if (!deployKey || !convexUrl) {
  console.error(
    "Missing CONVEX_DEPLOY_KEY and/or VITE_CONVEX_URL.\n" +
      "Add both in Cursor Dashboard → Cloud Agents → Secrets, then run: bun run env:setup",
  );
  process.exit(1);
}

const lines = [
  "# Generated by scripts/setup-env-local.ts — do not commit",
  envLine("CONVEX_DEPLOY_KEY", deployKey),
  envLine("VITE_CONVEX_URL", convexUrl),
  "",
];

writeFileSync(join(process.cwd(), ".env.local"), lines.join("\n"), "utf-8");
console.log("Wrote .env.local from environment variables.");
